#! /bin/sh
### BEGIN INIT INFO
# Provides: ubuntu-500px-wallpaper
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Ubuntu 500px wallpaper initiliazer
# Description: This file starts and stops ubuntu-500px-wallpaper
#
### END INIT INFO


case "$1" in
 start)
   # su joe -c $TOMCAT_DIR/bin/startup.sh
    sleep 2
    /home/$USER/.ubuntu-500px-wallpaper/wallpaper-manager.sh
   ;;
 stop)
    sleep 1
    /home/$USER/.ubuntu-500px-wallpaper/wallpaper-manager.sh # this script and logic will be changed
   ;;
 restart)
    /home/$USER/.ubuntu-500px-wallpaper/wallpaper-manager.sh # this script and logic will be changed
    ;;
 *)
   echo "Usage: ubuntu-500px-wallpaper-init {start|stop|restart}" >&2
   exit 3
   ;;
esac
